const path = require('node:path');
/* Fixtures are generated by tests/e2e/make-media.sh, not committed. */
const __MEDIA = (f) => path.join(__dirname, 'media', f);
const H = require('./lib/harness.cjs');
const app = H.app;
/* Regression suite for the reported defects:
     - L and C shortcuts swallowed while a control has focus
     - Space re-pressing the focused button instead of play/pause
     - the dead fullscreen button
     - one glyph per state for play / mute / fullscreen / autoplay
     - the play glyph going stale when a track loads paused
     - the playlist panel squeezing the control bar
     - the volume slider disappearing on a narrow window
     - the drop hint sticking after a drag that ends outside the window
     - the start window logo */
const fs = require('node:fs');
const DIR = path.join(require('node:os').tmpdir(), 'mt-e2e', 'reg');
fs.mkdirSync(DIR, { recursive: true });
const FILE = (f, n, t) => `(()=>{const b=atob('${fs.readFileSync(f).toString('base64')}');const a=new Uint8Array(b.length);for(let i=0;i<b.length;i++)a[i]=b.charCodeAt(i);return new File([a],'${n}',{type:'${t}'});})()`;

async function main() {
  fs.mkdirSync(DIR, { recursive: true });
  const win = await H.open({ width: 1100, height: 700 });
  const errors = win.harnessErrors;
  await H.fresh(win);

  const out = await win.webContents.executeJavaScript(`
  (async () => {
    const out = { steps: [] };
    const S = (k, v) => out.steps.push([k, v]);
    const wait = (ms) => new Promise((r) => setTimeout(r, ms));
    const stage = document.getElementById('stage');
    const side = document.getElementById('side');
    const bar = document.getElementById('bar');
    const player = document.getElementById('media');
    const $ = (id) => document.getElementById(id);
    const key = (k) => (document.activeElement || document).dispatchEvent(
      new KeyboardEvent('keydown', { key: k, bubbles: true, cancelable: true }));
    const glyphs = (id) => [...$(id).querySelectorAll('use')].filter((u) => getComputedStyle(u).display !== 'none').length;
    const glyphHref = (id) => { const u = [...$(id).querySelectorAll('use')].find((x) => getComputedStyle(x).display !== 'none');
      return u ? u.getAttribute('href') : 'none'; };
    const dts = (a) => { const d = new DataTransfer(); a.forEach((f) => d.items.add(f)); return d; };
    const drop = async (t, a) => { t.dispatchEvent(new DragEvent('drop', { dataTransfer: dts(a), bubbles: true, cancelable: true })); await wait(1200); };

    // ---- 1. the start window shows the logo, and it is really loaded ----
    const logo = document.querySelector('.logo');
    S('start: logo element', !!logo);
    S('start: logo loaded', logo ? logo.complete && logo.naturalWidth > 0 : false);
    S('start: logo keeps its aspect', logo ? Math.abs(logo.getBoundingClientRect().width / logo.getBoundingClientRect().height - logo.naturalWidth / logo.naturalHeight) < 0.02 : false);
    S('start: logo is displayed at a sane size', logo ? Math.round(logo.getBoundingClientRect().width) : 0);

    await drop(stage, [${FILE(__MEDIA('long.mp4'), 'holiday.mp4', 'video/mp4')},
                       ${FILE(__MEDIA('still.png'), 'sunset.png', 'image/png')},
                       ${FILE(__MEDIA('tone.mp3'), 'track.mp3', 'audio/mpeg')}]);
    key('p'); await wait(500);
    S('drops: three rows', $('list').children.length);

    // ---- 2. L and C must work even while a control holds focus ----
    $('play').focus();
    S('focus is on a control', document.activeElement === $('play'));
    const loopBefore = player.loop;
    key('l'); await wait(250);
    S('L works with a control focused', player.loop !== loopBefore);
    S('L lit the button', $('loop').classList.contains('on') === player.loop);
    const fitBefore = stage.dataset.fit;
    key('c'); await wait(250);
    S('C works with a control focused', stage.dataset.fit === 'cover' && fitBefore !== 'cover');
    S('C lit the button', $('fit-c').classList.contains('on'));
    key('d'); await wait(200);

    // ---- 3. Space must play/pause, never re-press the focused button ----
    $('loop').focus();
    const loopNow = player.loop;
    const pausedBefore = player.paused;
    key(' '); await wait(500);
    const pausedAfter = player.paused;
    S('space was paused before', pausedBefore);
    S('space toggled playback', pausedAfter !== pausedBefore);
    S('space did not re-press the focused button', player.loop === loopNow);
    S('space moved focus off the button', document.activeElement !== $('loop'));
    if (!pausedAfter) { key(' '); await wait(500); }

    // ---- 4. the fullscreen button works (it used to have no handler) ----
    $('fs').click(); await wait(900);
    S('fs button: entered', document.fullscreenElement === stage);
    S('fs button: shows the exit glyph', glyphHref('fs'));
    S('fs button: one glyph', glyphs('fs'));
    $('fs').click(); await wait(900);
    S('fs button: exited', !document.fullscreenElement);
    S('fs button: back to the enter glyph', glyphHref('fs'));

    // ---- 5. exactly one glyph per stateful control, in every state ----
    if (player.paused) { key(' '); await wait(500); }          // ensure playing
    S('glyph play while playing', glyphs('play') + ' ' + glyphHref('play') + ' paused=' + player.paused);
    key(' '); await wait(600);
    S('glyph play while paused', glyphs('play') + ' ' + glyphHref('play') + ' paused=' + player.paused);
    key(' '); await wait(600);
    S('glyph play after resume', glyphs('play') + ' ' + glyphHref('play') + ' paused=' + player.paused);
    key('m'); await wait(300);
    S('glyph mute while muted', glyphs('mute') + ' ' + glyphHref('mute'));
    key('m'); await wait(300);
    S('glyph mute while unmuted', glyphs('mute') + ' ' + glyphHref('mute'));
    key('a'); await wait(300);
    S('glyph autoplay while off', glyphs('autoplay') + ' ' + glyphHref('autoplay'));
    key('a'); await wait(300);
    S('glyph autoplay while on', glyphs('autoplay') + ' ' + glyphHref('autoplay'));

    // ---- 6. a track that loads paused must show the play glyph ----
    key('a'); await wait(250);                       // autoplay off
    key('.'); await wait(1200);                      // move on, loads paused
    S('paused track: really paused', player.paused);
    S('paused track: shows the play glyph', glyphHref('play'));
    S('paused track: one glyph', glyphs('play'));
    key('a'); await wait(250);                       // autoplay back on
    key('.'); await wait(1500);
    S('autoplay on: next track plays', player.paused === false);
    S('autoplay on: shows the pause glyph', glyphHref('play'));

    // ---- 7. the panel must not squeeze the control bar ----
    const barW = bar.getBoundingClientRect().width;
    const panelBottom = side.getBoundingClientRect().bottom;
    const barH = bar.getBoundingClientRect().height;
    /* the panel is full height and the bar lies on top of its lower edge */
    S('panel is full height', Math.abs(panelBottom - window.innerHeight) < 1);
    S('bar lies over the panel', getComputedStyle(bar).zIndex > getComputedStyle(side).zIndex);
    S('bar still has height', barH > 40);
    S('bar width value', Math.round(barW) + '/' + window.innerWidth);
    side.classList.remove('over');

    // ---- 8. the drop hint must not stick ----
    stage.dispatchEvent(new DragEvent('dragover', { dataTransfer: dts([]), bubbles: true, cancelable: true }));
    S('dragover marks the stage', stage.classList.contains('over'));
    // a drag released outside the window fires no drop and no useful dragleave
    document.dispatchEvent(new DragEvent('dragleave', { bubbles: true }));
    S('dragleave clears the hint', !stage.classList.contains('over') && !side.classList.contains('over'));

    // ---- 9. the instructions dialog ----
    const modal = $('help-modal');
    S('help: hidden at boot', modal.hidden);
    window.MediaMenu.send('info'); await wait(300);
    S('help: opens from the Info menu', modal.hidden === false);
    S('help: shortcut table present', document.querySelectorAll('.keys tr').length > 10);
    S('help: start page has no hint list', !document.querySelector('.drop .hint'));
    key('Escape'); await wait(300);
    S('help: esc closes it', modal.hidden);

    // ---- 10. l must not seek (the library's own shortcut map is cleared) ----
    S('library shortcuts cleared', JSON.stringify(player.keyShortcuts) === '{}');

    // ---- 11. clicking outside the panel closes it ----
    if (!stage.classList.contains('list')) { key('p'); await wait(300); }
    S('panel reopened', stage.classList.contains('list'));
    side.dispatchEvent(new PointerEvent('pointerdown', { bubbles: true }));
    await wait(300);
    S('click inside keeps it open', stage.classList.contains('list'));
    stage.dispatchEvent(new PointerEvent('pointerdown', { bubbles: true }));
    await wait(300);
    S('click outside closes it', stage.classList.contains('list') === false);

    return out;
  })()`, true);

  let pass = 0; const fail = [];
  for (const [k, v] of out.steps) {
    if (v === false || v === 0 || /none|false/.test(String(v)) && /glyph|paused track/.test(k)) fail.push(k + ' -> ' + v);
    else pass++;
    console.log(`  ${String(k).padEnd(40)} ${v}`);
  }
  // explicit expectation table for the boolean checks
  const expect = {
    'start: logo element': true, 'start: logo loaded': true, 'start: logo keeps its aspect': true,
    'start: logo is displayed at a sane size': 420,
    'drops: three rows': 3, 'focus is on a control': true,
    'L works with a control focused': true, 'C works with a control focused': true,
    'L lit the button': true, 'C lit the button': true,
    'space was paused before': false, 'space toggled playback': true,
    'space did not re-press the focused button': true, 'space moved focus off the button': true,
    'fs button: entered': true, 'fs button: shows the exit glyph': '#i-fs-exit', 'fs button: one glyph': 1,
    'fs button: exited': true, 'fs button: back to the enter glyph': '#i-fs',
    'glyph play while playing': '1 #i-pause paused=false', 'glyph play while paused': '1 #i-play paused=true',
    'glyph play after resume': '1 #i-pause paused=false',
    'glyph mute while muted': '1 #i-mute', 'glyph mute while unmuted': '1 #i-sound',
    'glyph autoplay while off': '1 #i-auto-off', 'glyph autoplay while on': '1 #i-auto',
    'paused track: really paused': true, 'paused track: shows the play glyph': '#i-play', 'paused track: one glyph': 1,
    'autoplay on: next track plays': true, 'autoplay on: shows the pause glyph': '#i-pause',
    'panel sits above the bar': true, 'bar is full width with the panel open': 1100,
    'dragover marks the stage': true, 'dragleave clears the hint': true,
    'help: hidden at boot': true, 'help: opens from the Info menu': true,
    'help: shortcut table present': true, 'help: start page has no hint list': true,
    'help: esc closes it': true, 'library shortcuts cleared': true,
    'panel reopened': true, 'click inside keeps it open': true, 'click outside closes it': true,
  };
  let bad = 0;
  console.log('');
  for (const [k, v] of out.steps) {
    if (!(k in expect)) continue;
    if (String(v) !== String(expect[k])) { console.log('  FAIL ' + k + '  got ' + JSON.stringify(v) + ' want ' + JSON.stringify(expect[k])); bad++; }
  }
  console.log(bad ? `\nFAILED ${bad} of ${Object.keys(expect).length}` : `\nPASSED all ${Object.keys(expect).length} regression checks`);
  if (errors.length) console.log('PAGE ERRORS: ' + errors.join(' | '));
  win.destroy();
  app.quit();
  if (bad) process.exitCode = 1;
}
main().catch((e) => { console.log('ERR ' + e.stack); app.quit(); process.exitCode = 1; });
