const path = require('node:path');
/* Fixtures are generated by tests/e2e/make-media.sh, not committed. */
const __MEDIA = (f) => path.join(__dirname, 'media', f);
const H = require('./lib/harness.cjs');
const app = H.app;
/* Verifies the four behaviours fixed in this round, in a real browser:
     1. `l` no longer seeks forward (the library's own shortcut map is cleared)
     2. the panel closes when clicking outside it, and stays open inside
     3. reorder reflows live and commits on drop; a cancelled drag restores
     4. the panel is full height with the bar on top, and the start window is
        just a dimmed logo
     5. the instructions dialog opens, lists the shortcuts, and closes */
const fs = require('node:fs');
const DIR = path.join(require('node:os').tmpdir(), 'mt-e2e', 'v4');
fs.mkdirSync(DIR, { recursive: true });
const FILE = (f, n, t) => `(()=>{const b=atob('${fs.readFileSync(f).toString('base64')}');const a=new Uint8Array(b.length);for(let i=0;i<b.length;i++)a[i]=b.charCodeAt(i);return new File([a],'${n}',{type:'${t}'});})()`;

async function main() {
  fs.mkdirSync(DIR, { recursive: true });
  const win = await H.open({ width: 1100, height: 700 });
  const errors = win.harnessErrors;
  await H.fresh(win);

  const out = await win.webContents.executeJavaScript(`
  (async () => {
    const out = { steps: [] };
    const S = (k, v) => out.steps.push([k, v]);
    try {
    const wait = (ms) => new Promise((r) => setTimeout(r, ms));
    const $ = (id) => document.getElementById(id);
    const stage = $('stage');
    const list = $('list');
    const player = $('media');
    const v = () => document.querySelector('media-provider > video');
    /* the provider <video> is created by the library on its own schedule */
    const ready = async () => { for (let i = 0; i < 40 && !v(); i++) await wait(100); return !!v(); };
    const key = (k) => (document.activeElement || document).dispatchEvent(
      new KeyboardEvent('keydown', { key: k, bubbles: true, cancelable: true }));
    const dts = (a) => { const d = new DataTransfer(); a.forEach((f) => d.items.add(f)); return d; };
    const drop = async (t, a) => { t.dispatchEvent(new DragEvent('drop', { dataTransfer: dts(a), bubbles: true, cancelable: true })); await wait(1300); };
    const names = () => [...list.children].map((li) => li.querySelector('.nm').textContent);

    // ---- 1. the library's shortcut map is gone ----
    S('library shortcuts cleared', JSON.stringify(player.keyShortcuts));

    // ---- 5. the start window is just a dimmed logo ----
    const logo = document.querySelector('.logo');
    S('start: logo present', !!logo);
    S('start: logo opacity', getComputedStyle(logo).opacity);
    S('start: no hint list on the start page', !!document.querySelector('.drop .hint'));
    S('start: centred', Math.abs((logo.getBoundingClientRect().left + logo.getBoundingClientRect().right) / 2 - window.innerWidth / 2) < 2);

    await drop(stage, [${FILE(__MEDIA('clip.mp4'), 'a.mp4', 'video/mp4')},
                       ${FILE(__MEDIA('still.png'), 'b.png', 'image/png')},
                       ${FILE(__MEDIA('tone.mp3'), 'c.mp3', 'audio/mpeg')},
                       ${FILE(__MEDIA('long.mp4'), 'd.mp4', 'video/mp4')},
                       ${FILE(__MEDIA('still.png'), 'e.png', 'image/png')}]);
    key('p'); await wait(500);
    S('playlist: five rows', names().join(','));

    // ---- 2. l must ONLY toggle loop ----
    S('video element ready', await ready());
    // Pause first: a playing video advances the timeline on its own, so any
    // movement after the keypress would be a seek, not playback.
    $('play').focus();
    if (!v().paused) { key(' '); await wait(500); }
    S('l: paused before the test', v().paused);
    const tBeforeKey = v().currentTime;
    const loop0 = player.loop;
    key('l');
    await wait(500);
    S('l: loop toggled', player.loop !== loop0);
    S('l: seek delta', (v().currentTime - tBeforeKey).toFixed(2));

    // ---- 3. panel closes on an outside click ----
    S('panel open', stage.classList.contains('list'));
    list.querySelector('.nm').click();          // inside: must stay open
    await wait(300);
    S('inside click keeps it open', stage.classList.contains('list'));
    $('bar').dispatchEvent(new PointerEvent('pointerdown', { bubbles: true }));  // bar: stays
    await wait(300);
    S('bar click keeps it open', stage.classList.contains('list'));
    stage.dispatchEvent(new PointerEvent('pointerdown', { bubbles: true, clientX: 700, clientY: 300 }));
    await wait(300);
    S('outside click closes it', stage.classList.contains('list') === false);

    // ---- 4. panel is full height, bar on top ----
    key('p'); await wait(400);
    const sideBox = $('side').getBoundingClientRect();
    const barBox = $('bar').getBoundingClientRect();
    S('panel is full height', Math.round(sideBox.bottom) === window.innerHeight);
    S('bar overlaps the panel', Math.round(barBox.top) > sideBox.top && Math.round(barBox.bottom) <= sideBox.bottom + 1);
    S('bar is full width', Math.round(barBox.width) === window.innerWidth);
    S('panel still scrolls to the bottom row', getComputedStyle(list).overflowY);
    key('p'); await wait(200);

    // ---- 5. reorder: live reflow, commit on drop ----
    key('p'); await wait(300);
    const rows = [...list.children];
    const dragged = rows[3];
    const box = (li) => li.getBoundingClientRect();
    rows[3].dispatchEvent(new DragEvent('dragstart', { dataTransfer: dts([]), bubbles: true, cancelable: true }));
    S('reorder: dragging flag', dragged.classList.contains('dragging'));
    S('reorder: no whole-player ring', stage.classList.contains('over') === false && $('side').classList.contains('over') === false);
    // the user's scenario: drag the 4th row onto the 2nd position, so hovering
    // the top half of row 1 must leave the node in slot 1 and push 2nd down
    const r1 = box(list.children[1]);
    list.dispatchEvent(new DragEvent('dragover', { dataTransfer: dts([]), bubbles: true, cancelable: true, clientY: r1.top + 4 }));
    await wait(150);
    S('reorder: node moved up live', [...list.children].indexOf(dragged));
    S('reorder: live order mid-drag', names().join(','));
    S('reorder: still no ring mid-drag', stage.classList.contains('over') === false);
    list.dispatchEvent(new DragEvent('drop', { dataTransfer: dts([]), bubbles: true, cancelable: true, clientY: r1.top + 4 }));
    await wait(400);
    S('reorder: committed order', names().join(','));
    S('reorder: no dragging flag after drop', [...list.children].some((li) => li.classList.contains('dragging')));
    S('reorder: counter', $('counter').textContent);

    // cancelled drag restores
    const before = names().join(',');
    const d2 = list.children[0];
    d2.dispatchEvent(new DragEvent('dragstart', { dataTransfer: dts([]), bubbles: true, cancelable: true }));
    const lastBox = box(list.children[list.children.length - 1]);
    list.dispatchEvent(new DragEvent('dragover', { dataTransfer: dts([]), bubbles: true, cancelable: true, clientY: lastBox.bottom - 2 }));
    await wait(120);
    S('reorder: node moved before cancel', [...list.children].indexOf(d2) !== 0);
    d2.dispatchEvent(new DragEvent('dragend', { dataTransfer: dts([]), bubbles: true, cancelable: true }));
    await wait(300);
    S('reorder: cancel restored order', names().join(',') === before);

    // ---- 6. the instructions dialog ----
    S('help: hidden at first', $('help-modal').hidden);
    $('help').click(); await wait(300);
    S('help: opens on click', $('help-modal').hidden === false);
    S('help: has shortcut rows', document.querySelectorAll('.keys tr').length);
    S('help: lists Space', $('help-modal').textContent.includes('play / pause'));
    S('help: lists the clear shortcut', $('help-modal').textContent.includes('clear the playlist'));
    S('help: no hint list on the start page any more', !document.querySelector('.drop .hint'));
    S('help: focus moved into the dialog', document.activeElement === $('help-close'));
    key('Escape'); await wait(300);
    S('help: esc closes', $('help-modal').hidden);
    S('help: esc did not close the panel', stage.classList.contains('list'));
    key('?'); await wait(250);
    S('help: ? opens', $('help-modal').hidden === false);
    key('i'); await wait(250);
    S('help: i closes', $('help-modal').hidden);
    $('help').click(); await wait(200);
    $('help-modal').dispatchEvent(new PointerEvent('pointerdown', { bubbles: true }));
    await wait(250);
    S('help: backdrop click closes', $('help-modal').hidden);

    } catch (err) { out.steps.push(['THREW', err.message]); }
    return out;
  })()`, true);

  const expect = {
    'library shortcuts cleared': '{}',
    'start: logo present': true,
    'start: logo opacity': '0.22',
    'start: no hint list on the start page': false,
    'start: centred': true,
    'playlist: five rows': 'a.mp4,b.png,c.mp3,d.mp4,e.png',
    'l: paused before the test': true,
    'l: loop toggled': true,
    'l: seek delta': '0.00',
    'panel open': true,
    'inside click keeps it open': true,
    'bar click keeps it open': true,
    'outside click closes it': true,
    'panel is full height': true,
    'bar overlaps the panel': true,
    'bar is full width': true,
    'panel still scrolls to the bottom row': 'auto',
    'reorder: dragging flag': true,
    'reorder: no whole-player ring': true,
    'reorder: node moved up live': 1,
    'reorder: live order mid-drag': 'a.mp4,d.mp4,b.png,c.mp3,e.png',
    'reorder: still no ring mid-drag': true,
    'reorder: committed order': 'a.mp4,d.mp4,b.png,c.mp3,e.png',
    'reorder: no dragging flag after drop': false,
    'reorder: node moved before cancel': true,
    'reorder: cancel restored order': true,
    'help: hidden at first': true,
    'help: opens on click': true,
    'help: lists Space': true,
    'help: lists the clear shortcut': true,
    'help: no hint list on the start page any more': true,
    'help: focus moved into the dialog': true,
    'help: esc closes': true,
    'help: esc did not close the panel': true,
    'help: ? opens': true,
    'help: i closes': true,
    'help: backdrop click closes': true,
  };
  let bad = 0;
  for (const [k, v] of out.steps) {
    const want = k in expect ? expect[k] : undefined;
    const ok = want === undefined || String(v) === String(want);
    if (!ok) bad++;
    console.log(`  ${String(k).padEnd(44)} ${v}${ok ? '' : '   <-- want ' + want}`);
  }
  const extra = out.steps.filter(([k]) => !(k in expect));
  if (extra.length) console.log('  (unchecked: ' + extra.map(([k]) => k).join(', ') + ')');
  console.log(bad ? `\nFAILED ${bad} of ${Object.keys(expect).length}` : `\nPASSED all ${Object.keys(expect).length} checks`);
  if (errors.length) console.log('PAGE ERRORS: ' + errors.join(' | '));

  // screenshots moved to v5shots/v5: the inline base64 payloads no longer
  // fit through executeJavaScript, so they fetch over the harness server
  console.log('  screenshots in ' + DIR);
  win.destroy();
  app.quit();
  if (bad) process.exitCode = 1;
}
main().catch((e) => { console.log('ERR ' + e.stack); app.quit(); process.exitCode = 1; });
