const path = require('node:path');
/* Fixtures are generated by tests/e2e/make-media.sh, not committed. */
const __MEDIA = (f) => path.join(__dirname, 'media', f);
const H = require('./lib/harness.cjs');
const app = H.app;
const fs = require('node:fs');
const FILE = (f, n, t) => `(()=>{const b=atob('${fs.readFileSync(f).toString('base64')}');const a=new Uint8Array(b.length);for(let i=0;i<b.length;i++)a[i]=bin.charCodeAt(i);return new File([a],'${n}',{type:'${t}'});})()`;

async function main() {
  const win = await H.open({ width: 1280, height: 800 });
  await new Promise((r) => setTimeout(r, 500));
  await win.webContents.executeJavaScript('localStorage.clear();');
  await new Promise((r) => setTimeout(r, 300));
  await win.webContents.executeJavaScript('location.reload();');
  await new Promise((r) => setTimeout(r, 1500));
  await win.webContents.executeJavaScript(`(async()=>{const w=ms=>new Promise(r=>setTimeout(r,ms));
    const d=new DataTransfer();
    const bin=atob('${fs.readFileSync(__MEDIA('clip.mp4')).toString('base64')}');
    const a=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)a[i]=bin.charCodeAt(i);
    d.items.add(new File([a],'sample.mp4',{type:'video/mp4'}));
    document.getElementById('stage').dispatchEvent(new DragEvent('drop',{dataTransfer:d,bubbles:true,cancelable:true}));
    await w(1500);
    document.getElementById('stage').classList.add('ui');
    await w(300);})()`, true);

  const WINS = [];
  for (const w of [1600, 1440, 1280, 1100, 980, 860, 760, 680, 600, 520, 440, 380]) {
    win.setContentSize(w, 700);
    await new Promise((r) => setTimeout(r, 450));
    const r = await win.webContents.executeJavaScript(`(() => {
      const bar = document.getElementById('bar');
      const row = bar.querySelector('.row');
      const kids = [...row.children];
      const last = kids[kids.length - 1].getBoundingClientRect();
      const vol = document.querySelector('.vds-volume');
      const vr = vol.getBoundingClientRect();
      const cs = getComputedStyle(vol);
      // only children sharing a visual line can collide; a wrapped line starts
      // at the left edge again
      const overlap = kids.some((k, i) => {
        if (!i) return false;
        const a = kids[i-1].getBoundingClientRect(), b = k.getBoundingClientRect();
        return Math.abs(a.top - b.top) < 2 && b.left < a.right - 0.5;
      });
      const right = kids[kids.length - 1];
      const rdump = [...right.children].map((k) => (k.id || k.className) + '[' + Math.round(k.getBoundingClientRect().left) + '..' + Math.round(k.getBoundingClientRect().right) + ']').join(' ');
      const dump = kids.map((k) => k.tagName.toLowerCase() + '.' + k.className + '[' + Math.round(k.getBoundingClientRect().left) + '..' + Math.round(k.getBoundingClientRect().right) + ']').join(' ');
      const widest = [...row.children].map((k) => ({ n: k.className, r: Math.round(k.getBoundingClientRect().right), w: Math.round(k.getBoundingClientRect().width) }))
        .filter((x) => x.r > window.innerWidth - 12).map((x) => x.n + ' w' + x.w + ' r' + x.r).join(', ');
      const over = [...row.querySelectorAll('*')].filter((e) => e.getBoundingClientRect().right > window.innerWidth + 0.5)
        .map((e) => e.tagName.toLowerCase() + '.' + (e.className.baseVal !== undefined ? e.className.baseVal : e.className).toString().split(' ')[0] + '@' + Math.round(e.getBoundingClientRect().right));
      return {
        overflowers: over.slice(0, 4).join(','),
        win: window.innerWidth,
        rowScroll: row.scrollWidth, rowClient: row.clientWidth,
        lastRight: Math.round(last.right), clipped: last.right > window.innerWidth + 0.5,
        volW: Math.round(vr.width), volVisible: cs.display !== 'none' && vr.width > 20,
        overlap, widest, dump, rdump, rscroll: right.scrollWidth, rclient: right.clientWidth,
        barH: Math.round(bar.getBoundingClientRect().height),
      };
    })()`);
    const bad = r.clipped || !r.volVisible || r.overlap;
    WINS.push({ w, bad });
    console.log(`  ${String(r.win).padStart(5)}px  row ${r.rowScroll}/${r.rowClient}  lastRight ${String(r.lastRight).padStart(5)}  vol ${String(r.volW).padStart(3)}px ${r.volVisible ? 'vis' : 'GONE'}  ${r.overlap ? 'OVERLAP' : ''} ${r.dump ? r.dump + ' | RIGHT ' + r.rdump + ' scroll ' + r.rscroll + '/' + r.rclient + ' ' : ''}${r.overflowers ? 'Ovf:' + r.overflowers + ' ' : ''}${bad ? '  <-- FAIL' : ''}`);
  }
  /* One verdict line, like every other suite: a bare list of measurements
     cannot be grepped for pass/fail and a silent regression would go unnoticed. */
  const failed = WINS.filter((w) => w.bad).length;
  console.log(failed ? `FAILED ${failed} of ${WINS.length} widths` : `PASSED all ${WINS.length} widths`);
  if (failed) process.exitCode = 1;
  win.destroy();
  app.quit();
}
main().catch((e) => { console.log('ERR ' + e.stack); process.exitCode = 1; app.quit(); });
